
language: php

git:
    depth: 5

php:
    - 7.1
    - 7.2
    - 7.3

install:
    - travis_retry composer clear-cache
    - travis_retry composer self-update
    - travis_retry composer install

script:
    - composer lint
    - composer test

